POST http://localhost:3003/api/blogs HTTP/1.1 
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFvZXUiLCJpZCI6IjYzODcxMjE0MTQ2YTNmNzUxYTEwOGZhZCIsImlhdCI6MTY2OTc5NzM1MSwiZXhwIjoxNjY5ODAwOTUxfQ.P0WxSKYTcuXO2nyXtzmYMwpXk7-dN2OPAghysp1RbFE

{
  "title": "Leptos > React",
  "author": "Smart guy",
  "url": "www.leptos.com",
  "likes": 1000
} 