DELETE http://localhost:3003/api/blogs/6385db137ec4994520aee6b2
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzODUwZGMwNzBmY2U5MmE4Nzc5NTE2YyIsImlhdCI6MTY2OTcxNDQ4MCwiZXhwIjoxNjY5NzE4MDgwfQ.vQYDFJKBLXHB_BTbTrw6Hpiw92qhCAoHyamG1twuHm0