GET http://localhost:3003/api/blogs HTTP/1.1
Content-type: application/json
// Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFvZXUiLCJpZCI6IjYzODcxMjE0MTQ2YTNmNzUxYTEwOGZhZCIsImlhdCI6MTY2OTgwNjIzMiwiZXhwIjoxNjY5ODA5ODMyfQ.LVaYeNwnL6wOGcF1TzGWNz74K0vd1iqBoK09a_PkxC0