PUT http://localhost:3003/api/blogs/63850dc170fce92a877951a1 HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFvZXUiLCJpZCI6IjYzODRmY2E2Yjc2YWUzZTRmMjQxNmRhZCIsImlhdCI6MTY2OTY1OTg3MH0.HkNpa36cGUCEUmDru4JxqBb6_4NqFIC2IZCsvjCHWZI

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 5
}